services:
  db:
    image: postgres:17
    container_name: pdf_postgres
    restart: always
    environment:
      - POSTGRES_DB=pdf_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: pdf_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # Senin settings.py içindeki os.getenv isimleriyle birebir aynı olmalı
      - DB_NAME=pdf_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres_pass
      - DB_HOST=db  # Burası kritik: Docker içindeki 'db' servisine bakmalı
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: